### PR TITLE
Fix broken ruby tests

### PR DESCRIPTION
**Pull request by alex-kuck**
There are missing brackets in some of the tests, as mentioned in #17. This should fix it.

### CODE REVIEW

**Review by Gorcenski — CHANGES_REQUESTED** [review]
Thanks for catching the errant tests!

There are a lot of whitespace changes that create a double-indent issue that might cause folks to throw linting errors. Can you remove those whitespace changes and keep the functional changes on lines 36, 49, and 76? I'm not a Ruby expert, but if we need them for style adherence it should be possible to make a separate commit that will be easier to diff and merge.

Thank you!

**Comment by alex-kuck** [comment]
Sure, will do that!

**Comment by alex-kuck** [comment]
@Gorcenski I have updated the PR as asked.

**Comment by Gorcenski** [comment]
Thank you!

**Pull request merged**
